apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels: # these labels are deployment labels 
    app: mongodb
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # this match labels should match with pod
      app: mongodb
      tier: db
      project: roboshop
  template: # this is pod definition
    metadata:
      labels:
        app: mongodb
        tier: db
        project: roboshop
    spec:
      containers:
        - name: mongodb
          image: sivajanardhan/mongodb:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    tier: db
    project: roboshop
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017 # this port belongs to service
    targetPort: 27017 # this port belongs to container          
